// server/constants.js
module.exports = {
    MAP_WIDTH: 1600,
    MAP_HEIGHT: 1200,
    PLAYER_HEALTH: 100,
    PLAYER_RADIUS: 15,
    PLAYER_SPEED: 3,
    DASH_COOLDOWN: 5000,
    DASH_SPEED_MULTIPLIER: 3,
    DASH_DURATION: 200,
    HEALTH_PACK_AMOUNT: 50,
    SPEED_BOOST_AMOUNT: 1.5,
    SPEED_BOOST_DURATION: 5000,
};